theme: jekyll-theme-cayman

title: "AndyDune pages"
description: "Words inside sentences about my code, my interests and me."

twitter_username: andydune
github_username:  andydune

# Build settings
markdown: kramdown
